-- Hangman: words with tags, difficulty scoring, and the shared leaderboard.
-- Every object uses the hangman_ prefix because the project is shared with
-- Wallet, Family Games, and Habit Tracker.

create type public.hangman_difficulty as enum ('easy', 'medium', 'hard');

-- Letter frequencies (0-1) per locale, used to score word difficulty.
create table public.hangman_letter_frequencies (
  letter character(1) not null,
  locale text not null,
  frequency numeric(3, 2) not null,
  primary key (letter, locale),
  constraint hangman_letter_frequencies_frequency_check
    check (frequency >= 0 and frequency <= 1)
);

comment on table public.hangman_letter_frequencies is
  'Letter frequency data by language for difficulty calculation';

insert into public.hangman_letter_frequencies (letter, locale, frequency) values
  ('E', 'en', 1.00), ('T', 'en', 0.91), ('A', 'en', 0.82), ('O', 'en', 0.75),
  ('I', 'en', 0.70), ('N', 'en', 0.67), ('S', 'en', 0.63), ('H', 'en', 0.61),
  ('R', 'en', 0.60), ('D', 'en', 0.43), ('L', 'en', 0.40), ('C', 'en', 0.28),
  ('U', 'en', 0.28), ('M', 'en', 0.24), ('W', 'en', 0.24), ('F', 'en', 0.22),
  ('G', 'en', 0.20), ('Y', 'en', 0.20), ('P', 'en', 0.19), ('B', 'en', 0.15),
  ('V', 'en', 0.10), ('K', 'en', 0.08), ('J', 'en', 0.02), ('X', 'en', 0.02),
  ('Q', 'en', 0.01), ('Z', 'en', 0.01),
  ('E', 'es', 1.00), ('A', 'es', 0.95), ('O', 'es', 0.87), ('S', 'es', 0.80),
  ('R', 'es', 0.75), ('N', 'es', 0.71), ('I', 'es', 0.63), ('D', 'es', 0.58),
  ('L', 'es', 0.52), ('C', 'es', 0.47), ('T', 'es', 0.46), ('U', 'es', 0.45),
  ('M', 'es', 0.32), ('P', 'es', 0.28), ('B', 'es', 0.14), ('G', 'es', 0.10),
  ('V', 'es', 0.09), ('Y', 'es', 0.09), ('Q', 'es', 0.09), ('H', 'es', 0.07),
  ('F', 'es', 0.07), ('Z', 'es', 0.05), ('J', 'es', 0.04), ('Ñ', 'es', 0.03),
  ('X', 'es', 0.02), ('W', 'es', 0.00), ('K', 'es', 0.00);

create table public.hangman_words (
  id bigint generated by default as identity primary key,
  word text not null,
  difficulty_value integer not null,
  locale text not null default 'en',
  created_at timestamptz not null default now(),
  constraint hangman_words_word_locale_unique unique (word, locale),
  constraint hangman_words_difficulty_value_check
    check (difficulty_value >= 1 and difficulty_value <= 100)
);

comment on table public.hangman_words is
  'Words for the Hangman game with difficulty values and locale';

create table public.hangman_tags (
  id bigint generated by default as identity primary key,
  tag text not null,
  locale text not null default 'en',
  created_at timestamptz not null default now(),
  constraint hangman_tags_tag_locale_unique unique (tag, locale)
);

comment on table public.hangman_tags is 'Descriptive tags/hints for words';

create table public.hangman_word_tags (
  word_id bigint not null references public.hangman_words (id) on delete cascade,
  tag_id bigint not null references public.hangman_tags (id) on delete cascade,
  primary key (word_id, tag_id)
);

comment on table public.hangman_word_tags is 'Links words to their tags';

create table public.hangman_game_records (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null default auth.uid()
    references auth.users (id) on delete cascade,
  has_timed_mode_enabled boolean,
  difficulty public.hangman_difficulty,
  points bigint,
  words bigint,
  time_playing bigint
);

create index hangman_words_locale_idx on public.hangman_words (locale);
create index hangman_words_difficulty_idx on public.hangman_words (difficulty_value);
create index hangman_words_locale_difficulty_idx
  on public.hangman_words (locale, difficulty_value);
create index hangman_tags_locale_idx on public.hangman_tags (locale);
create index hangman_word_tags_word_id_idx on public.hangman_word_tags (word_id);
create index hangman_word_tags_tag_id_idx on public.hangman_word_tags (tag_id);
create index hangman_game_records_created_at_idx
  on public.hangman_game_records (created_at desc);
create index hangman_game_records_points_idx
  on public.hangman_game_records (points desc);
create index hangman_game_records_difficulty_points_idx
  on public.hangman_game_records (difficulty, points desc);
create index hangman_game_records_user_id_idx
  on public.hangman_game_records (user_id);

-- Difficulty (0-1): 40% unique letter ratio, 35% letter rarity, 25% length.
create or replace function public.hangman_calculate_word_difficulty(
  word_text text,
  word_locale text default 'en'
)
returns numeric
language plpgsql
stable
set search_path = public
as $$
declare
  word_upper text := upper(word_text);
  word_length int := length(upper(word_text));
  unique_letters int;
  unique_ratio numeric := 0;
  avg_letter_rarity numeric;
  length_score numeric;
begin
  select count(distinct letter_char) into unique_letters
  from regexp_split_to_table(word_upper, '') as letter_char
  where letter_char ~ '[A-ZÑÁÉÍÓÚÜ]';

  if word_length > 0 then
    unique_ratio := unique_letters::numeric / word_length::numeric;
  end if;

  select coalesce(avg(1.0 - coalesce(lf.frequency, 0.5)), 0.5)
  into avg_letter_rarity
  from regexp_split_to_table(word_upper, '') as letter_char
  left join public.hangman_letter_frequencies lf
    on lf.letter = letter_char and lf.locale = word_locale
  where letter_char ~ '[A-ZÑÁÉÍÓÚÜ]';

  length_score := greatest(0.0, least(1.0, (word_length::numeric - 3.0) / 12.0));

  return least(1.0, greatest(0.0,
    unique_ratio * 0.40 + avg_letter_rarity * 0.35 + length_score * 0.25
  ));
end;
$$;

comment on function public.hangman_calculate_word_difficulty(text, text) is
  'Calculates word difficulty (0-1) based on unique letters, length, and letter rarity';

create or replace function public.hangman_trigger_calculate_word_difficulty()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'INSERT' or new.word <> old.word or new.locale <> old.locale then
    new.difficulty_value := greatest(1, round(
      public.hangman_calculate_word_difficulty(new.word, new.locale) * 100
    ));
  end if;
  return new;
end;
$$;

create trigger hangman_words_calculate_difficulty
  before insert or update on public.hangman_words
  for each row execute function public.hangman_trigger_calculate_word_difficulty();

create or replace function public.hangman_update_all_word_difficulties()
returns table (updated_count integer)
language plpgsql
set search_path = public
as $$
declare
  affected_rows int := 0;
begin
  update public.hangman_words w
  set difficulty_value = greatest(1, round(
    public.hangman_calculate_word_difficulty(w.word, w.locale) * 100
  ));
  get diagnostics affected_rows = row_count;
  return query select affected_rows;
end;
$$;

create or replace function public.hangman_update_word_difficulties_by_locale(
  target_locale text
)
returns table (updated_count integer)
language plpgsql
set search_path = public
as $$
declare
  affected_rows int := 0;
begin
  update public.hangman_words w
  set difficulty_value = greatest(1, round(
    public.hangman_calculate_word_difficulty(w.word, w.locale) * 100
  ))
  where w.locale = target_locale;
  get diagnostics affected_rows = row_count;
  return query select affected_rows;
end;
$$;

create view public.hangman_words_with_tags
with (security_invoker = on) as
select
  w.id,
  w.word,
  w.difficulty_value,
  w.locale,
  w.created_at,
  coalesce(
    array_agg(t.tag order by t.tag) filter (where t.tag is not null),
    array[]::text[]
  ) as tags
from public.hangman_words w
left join public.hangman_word_tags wt on wt.word_id = w.id
left join public.hangman_tags t on t.id = wt.tag_id
group by w.id, w.word, w.difficulty_value, w.locale, w.created_at;

-- Runs as the owner so the leaderboard can read usernames from auth.users.
-- Only the username is taken from auth.users.
create view public.hangman_game_records_with_usernames
with (security_invoker = off) as
select
  gr.id,
  gr.user_id,
  gr.created_at,
  gr.has_timed_mode_enabled,
  gr.difficulty,
  gr.points,
  gr.words,
  gr.time_playing,
  coalesce(au.raw_user_meta_data ->> 'username', 'Player') as username
from public.hangman_game_records gr
left join auth.users au on au.id = gr.user_id;

alter table public.hangman_letter_frequencies enable row level security;
alter table public.hangman_words enable row level security;
alter table public.hangman_tags enable row level security;
alter table public.hangman_word_tags enable row level security;
alter table public.hangman_game_records enable row level security;

create policy hangman_letter_frequencies_select on public.hangman_letter_frequencies
  for select to authenticated using (true);

create policy hangman_words_select on public.hangman_words
  for select to authenticated using (true);

create policy hangman_tags_select on public.hangman_tags
  for select to authenticated using (true);

create policy hangman_word_tags_select on public.hangman_word_tags
  for select to authenticated using (true);

create policy hangman_game_records_select on public.hangman_game_records
  for select to authenticated using (true);

create policy hangman_game_records_insert on public.hangman_game_records
  for insert to authenticated with check ((select auth.uid()) = user_id);

revoke all on public.hangman_letter_frequencies from anon, public;
revoke all on public.hangman_words from anon, public;
revoke all on public.hangman_tags from anon, public;
revoke all on public.hangman_word_tags from anon, public;
revoke all on public.hangman_game_records from anon, public;
revoke all on public.hangman_words_with_tags from anon, public;
revoke all on public.hangman_game_records_with_usernames from anon, public;

grant select on public.hangman_letter_frequencies to authenticated;
grant select on public.hangman_words to authenticated;
grant select on public.hangman_tags to authenticated;
grant select on public.hangman_word_tags to authenticated;
grant select, insert on public.hangman_game_records to authenticated;
grant select on public.hangman_words_with_tags to authenticated;
grant select on public.hangman_game_records_with_usernames to authenticated;

-- scripts/seed_words.dart uses the service role to sync words and tags.
grant all on public.hangman_letter_frequencies to service_role;
grant all on public.hangman_words to service_role;
grant all on public.hangman_tags to service_role;
grant all on public.hangman_word_tags to service_role;
grant all on public.hangman_game_records to service_role;
grant select on public.hangman_words_with_tags to service_role;
grant select on public.hangman_game_records_with_usernames to service_role;

revoke all on function public.hangman_calculate_word_difficulty(text, text) from public, anon;
revoke all on function public.hangman_trigger_calculate_word_difficulty() from public, anon, authenticated;
revoke all on function public.hangman_update_all_word_difficulties() from public, anon, authenticated;
revoke all on function public.hangman_update_word_difficulties_by_locale(text) from public, anon, authenticated;

grant execute on function public.hangman_calculate_word_difficulty(text, text) to authenticated, service_role;
grant execute on function public.hangman_update_all_word_difficulties() to service_role;
grant execute on function public.hangman_update_word_difficulties_by_locale(text) to service_role;
